name: CI/CD

on:
    push:
        branches: [ main ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

            - name: Set up Node.js
              uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # 6.3.0
              with:
                node-version: '24.x'

            - name: Set up Aspire
              run: |
                curl -sSL https://aspire.dev/install.sh | bash
              shell: bash

            - name: Install Node Dependencis
              run: |
                npm ci
              shell: bash
              