name: CI/CD

on:
    push:
        branches: [ main ]

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: false

env:
    CARGO_TERM_COLOR: always

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

            - name: Set up .NET
              uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # 5.2.0
              with:
                dotnet-version: 10.x

            - name: Configure WASM tooling
              run: |
                rustup target add wasm32-unknown-unknown
                rustup component add llvm-tools-preview
                cargo install trunk wasm-bindgen-cli cargo-llvm-cov
              shell: bash
              
            - name: Set up Aspire
              run: curl -sSL https://aspire.dev/install.sh | bash
              shell: bash

            - name: Quality - Code Formatting
              run: cargo fmt --check
              shell: bash
              working-directory: ui

            - name: Quality - Unit Tests with Coverage
              run: cargo llvm-cov --html
              shell: bash
              working-directory: ui

            - name: Upload Code Coverage Report
              if: always()
              uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
              with:
                name: ui-code-coverage-report
                path: ui/target/llvm-cov/html/
                retention-days: 30

            - name: Build Application
              run: trunk build --release
              shell: bash
              working-directory: ui

              